# -*- coding: utf-8 -*-
"""Analisis_Portafolios.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OHRI3VCCTIOc3M4eLd18hLDRVqrlBv_n
"""

#!pip install streamlit pandas numpy yfinance matplotlib

#Importación las librerías

import streamlit as st
import pandas as pd
import numpy as np
import yfinance as yf
import matplotlib.pyplot as plt

# Encabezado principal

import streamlit as st
import pandas as pd
import numpy as np
import yfinance as yf
import matplotlib.pyplot as plt

st.title ("💼 Smart Portafolio")
st.write("""
Esta aplicación analiza un portafolio de inversión aplicando la **Teoría Moderna de Portafolios de Markowitz**.
Se simulan tres escenarios (Conservador, Moderado y Agresivo) para observar cómo varían el riesgo, el rendimiento y la composición de activos.
Los datos se obtienen directamente desde **Yahoo Finance**, y los activos seleccionados pertenecen al sector tecnológico.
""")

# Configuración de entradas

st.sidebar.markdown("## ⚙️ Configuración del Análisis")

# Entrada libre de tickers
tickers_input = st.sidebar.text_input(
    "Empresas (separa por comas):",
    value="AAPL, META"
)

# Convertir texto en lista
tickers = [t.strip().upper() for t in tickers_input.split(",") if t.strip() != ""]


# Rango de fechas
fecha_inicio = st.sidebar.date_input("📅 Fecha inicial", pd.to_datetime("2020-01-01"))
fecha_fin = st.sidebar.date_input("📅 Fecha final", pd.to_datetime("2023-12-31"))

# Inversión inicial
inversion_inicial = st.sidebar.number_input("💰 Inversión Inicial (USD)", min_value=1000, value=10000, step=500)

# Frecuencia temporal
frecuencia = st.sidebar.selectbox("⏱️ Frecuencia Temporal", ["Diaria", "Semanal", "Mensual"])

# Tipo de escenario
escenario = st.sidebar.selectbox("📊 Escenario de Inversión", ["Conservador", "Moderado", "Agresivo"])

# Botón para ejecutar
descargar = st.sidebar.button("📥 Descargar y Analizar")


# Descarga de datos

data = yf.download(tickers, start=fecha_inicio, end=fecha_fin)["Close"]
st.subheader("📊 Datos Históricos Descargados")
st.dataframe(data.tail())

# Visualización de Precios

st.subheader("📈 Evolución Histórica de Precios")
fig1, ax1 = plt.subplots(figsize=(10, 4))
data.plot(ax=ax1)
plt.title("Evolución de Precios Ajustados")
plt.xlabel("Fecha")
plt.ylabel("Precio (USD)")
st.pyplot(fig1)

# Cálculo de rendimientos

returns = data.pct_change().dropna()
mean_returns = returns.mean() * 252
cov_matrix = returns.cov() * 252

# Estadísticas generales
st.dataframe(returns.describe().T)

# Escenario de inversión

st.sidebar.header("💰 Escenario de Inversión")
escenario = st.sidebar.selectbox("Seleccione el tipo de portafolio", ["Conservador", "Moderado", "Agresivo"])

escenarios = {
    "Conservador": np.array([0.6, 0.3, 0.1])[:len(tickers)],
    "Moderado": np.array([0.4, 0.4, 0.2])[:len(tickers)],
    "Agresivo": np.array([0.2, 0.3, 0.5])[:len(tickers)]
}

weights = escenarios[escenario]
weights = weights / np.sum(weights)

# Cálculos del portafolio

port_return = np.dot(weights, mean_returns)
port_volatility = np.sqrt(np.dot(weights.T, np.dot(cov_matrix, weights)))
sharpe_ratio = port_return / port_volatility

# Retorno acumulado y evolución monetaria

returns["Portfolio"] = (returns[tickers] * weights).sum(axis=1)
valor_portafolio = (1 + returns["Portfolio"]).cumprod() * inversion_inicial

# Resultados

st.subheader(f"📊 Resultados del Portafolio ({escenario})")
st.write("**Pesos del Portafolio:**", dict(zip(tickers, weights.round(2))))
st.write(f"**Rendimiento Esperado:** {port_return:.2%}")
st.write(f"**Volatilidad Esperada:** {port_volatility:.2%}")
st.write(f"**Sharpe Ratio:** {sharpe_ratio:.2f}")

# Evolución del valor monetario

st.subheader("💵 Evolución del Valor del Portafolio")
fig2, ax2 = plt.subplots(figsize=(10, 4))
valor_portafolio.plot(ax=ax2, color='green')
plt.title("Evolución del valor monetario del portafolio")
plt.xlabel("Fecha")
plt.ylabel("Valor (USD)")
st.pyplot(fig2)

# Diagrama riesgo - retorno

st.subheader("📊 Diagrama Riesgo - Retorno")
fig3, ax3 = plt.subplots()
ax3.scatter(port_volatility, port_return, c='blue', s=100)
ax3.set_xlabel("Volatilidad (Riesgo)")
ax3.set_ylabel("Rendimiento Esperado")
ax3.set_title("Diagrama Riesgo - Retorno")
st.pyplot(fig3)

#  Correlaciones

st.subheader("🔥 Matriz de Correlaciones entre Activos")
corr_matrix = returns[tickers].corr()
st.dataframe(corr_matrix)

fig4, ax4 = plt.subplots()
cax = ax4.imshow(corr_matrix, cmap="coolwarm", interpolation="nearest")
plt.title("Heatmap de Correlaciones")
plt.colorbar(cax)
ax4.set_xticks(range(len(corr_matrix)))
ax4.set_xticklabels(corr_matrix.columns, rotation=45)
ax4.set_yticks(range(len(corr_matrix)))
ax4.set_yticklabels(corr_matrix.columns)
st.pyplot(fig4)

# Visualización del portafolio

st.subheader("🥧 Distribución del Portafolio por Escenario")

fig, ax = plt.subplots()
ax.pie(weights, labels=tickers, autopct="%1.1f%%", startangle=90)
ax.set_title(f"Distribución del Portafolio ({escenario})")
st.pyplot(fig)

# Distribución de pesos por escenario

st.subheader("📊 Comparación de Escenarios de Inversión")

fig_all, axs = plt.subplots(1, 3, figsize=(12, 4))
for i, (nombre, w) in enumerate({
    "Conservador": np.array([0.6, 0.3, 0.1])[:len(tickers)],
    "Moderado": np.array([0.4, 0.4, 0.2])[:len(tickers)],
    "Agresivo": np.array([0.2, 0.3, 0.5])[:len(tickers)]
}.items()):
    w = w / np.sum(w)
    axs[i].pie(w, labels=tickers, autopct='%1.1f%%', startangle=90)
    axs[i].set_title(nombre)

plt.suptitle("Distribución de Pesos por Tipo de Portafolio")
st.pyplot(fig_all)
